main: main.cpp copy.cpp copy.h epoll.h epoll.cpp epollfd.h epollfd.cpp aoperation.h aoperation.cpp aaccept.h aaccept.cpp awrite.h awrite.cpp buffer.h buffer.cpp aread.h aread.cpp binary_expression.h expression.h var.h autofd.h autofd.cpp
	g++ -o main -std=c++0x -g -lrt main.cpp copy.cpp epoll.cpp epollfd.cpp aoperation.cpp aaccept.cpp awrite.cpp buffer.cpp aread.cpp autofd.cpp
