main: main.cpp epollfd.cpp buffer.cpp aread.cpp awrite.cpp aaccept.cpp aoperation.cpp epoll.cpp
	g++ -std=c++0x main.cpp epollfd.cpp buffer.cpp aread.cpp awrite.cpp aaccept.cpp aoperation.cpp epoll.cpp -o main -g
