#!/bin/sh

scan() {
    for name in "$@"; do
        if [ -d "$name" ]; then
            scan "$name"/*
        fi
        if ! [ -e "$name" ]; then
            if [ -L "$name" ]; then
                echo "Broken symbolic link: $name"
            fi
        fi
    done
}

scan "$@"
