#!/bin/sh

scan() {
    for name in "$@"; do
        #echo "Scan $name"
        if [ -e "$name" ]; then
            echo "$name"
            if [ -d "$name" ]; then
                scan "$name"/*
            fi
        fi
    done
}

scan "$@"
